### PR TITLE
QAnything As LLM Method

### PR DESCRIPTION
**Pull request by SanBingYouYong**
Integrate QAnything API as a way to obtain LLM response to input question. 

Assumes QAnything is set up and running in the same machine (localhost) thus did not include support for api key. 

Assumes at least one knowledge base is set up and the id is added in `default_kb_ids` list.

### CODE REVIEW

**Comment by SanBingYouYong** [comment]
理论上这算"加入RAG"吧哈哈哈, Qanything repo在这儿: https://github.com/netease-youdao/QAnything

**Comment by SanBingYouYong** [comment]
Just merged some incoming changes, now up to date again.

**Comment by SanBingYouYong** [comment]
@Kedreamix 哥们儿接受PR吗, 看起来没有合并其他PR的记录, 不接受PR我就关了 :(

**Comment by SanBingYouYong** [comment]
目前的`webui.py`中默认call的是`llm.generate(question, system)`, 但不少LLM实现里的.generate方法只接受一个参数会造成报错

亦或者是我集成方式理解的有问题?

**Comment by Kedreamix** [comment]
抱歉哈，没注意PR，后面的llm.generate的部分我是希望写成统一的，就是没有参数可以默认，我会测试一下接受PR哒，感谢

**Comment by Kedreamix** [comment]
由于我的疏忽，所以之前没注意，现在我已merge进去，感谢你的PR，我也会尝试一下QAnything的方式，感谢你的贡献！！！

**Pull request merged**
